# Generated by Django 3.1.3 on 2020-11-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_img',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
